### ISSUE TITLE
AMI does not exist – which region to use? 

### ISSUE THREAD

**Issue by elsbrock** [gerlacdt/nomad-example#1]
Thanks for this example! I was trying to get this running and stumbled over the AMI not being found. Can you update the README to tell which region I need to start this in?

**Comment by gerlacdt** [comment]
Hi,

the region is eu-west-1.

The name of the AMI is `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20170202`. AMI-Id is `ami-98ecb7fe`

Sometimes Amazon deprecates AMIs and deletes them but the AMI above should be there.

I updated the README.

**Comment by gerlacdt** [comment]
README contains now the used AMI and aws-region (eu-west-1)
